
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NE = 31;
  public static final int LT = 30;
  public static final int ELSE = 23;
  public static final int PLUS = 14;
  public static final int ENDIF = 24;
  public static final int THEN = 21;
  public static final int STATUS = 9;
  public static final int SIGN = 10;
  public static final int ABLT = 26;
  public static final int POW = 18;
  public static final int IF = 20;
  public static final int GT = 29;
  public static final int LE = 28;
  public static final int CB = 13;
  public static final int OB = 12;
  public static final int STRING = 3;
  public static final int COMMA = 7;
  public static final int ABGT = 25;
  public static final int EOF = 0;
  public static final int NUMBER = 5;
  public static final int ELSEIF = 22;
  public static final int SET = 6;
  public static final int DIV = 17;
  public static final int ABS = 11;
  public static final int GE = 27;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int ZERO_NAME_VAR = 4;
  public static final int NAME_VAR = 2;
  public static final int EQ = 32;
  public static final int MUL = 16;
  public static final int ASIG = 8;
  public static final int UMINUS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME_VAR",
  "STRING",
  "ZERO_NAME_VAR",
  "NUMBER",
  "SET",
  "COMMA",
  "ASIG",
  "STATUS",
  "SIGN",
  "ABS",
  "OB",
  "CB",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "POW",
  "UMINUS",
  "IF",
  "THEN",
  "ELSEIF",
  "ELSE",
  "ENDIF",
  "ABGT",
  "ABLT",
  "GE",
  "LE",
  "GT",
  "LT",
  "NE",
  "EQ"
  };
}

