
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 23 14:21:23 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GE = 26;
  public static final int UMINUS = 8;
  public static final int INT = 20;
  public static final int FOR = 36;
  public static final int MINUS = 5;
  public static final int INT_CAST = 43;
  public static final int OCC = 14;
  public static final int OCB = 12;
  public static final int NOT = 31;
  public static final int AND = 30;
  public static final int LT = 23;
  public static final int IN = 41;
  public static final int OR = 29;
  public static final int COMMA = 17;
  public static final int INC = 34;
  public static final int DIV = 7;
  public static final int PLUS = 4;
  public static final int CB = 11;
  public static final int IF = 32;
  public static final int LE = 24;
  public static final int EOF = 0;
  public static final int ASIG = 22;
  public static final int OB = 10;
  public static final int error = 1;
  public static final int MUL = 6;
  public static final int MOD = 9;
  public static final int FLOAT_CAST = 44;
  public static final int EQ = 27;
  public static final int CCC = 15;
  public static final int CCB = 13;
  public static final int ELSE = 33;
  public static final int TO = 37;
  public static final int WHILE = 42;
  public static final int FLOAT = 21;
  public static final int NE = 28;
  public static final int VAR_NAME = 18;
  public static final int INT_NUM = 2;
  public static final int DOWNTO = 38;
  public static final int DEC = 35;
  public static final int GT = 25;
  public static final int FLOAT_NUM = 3;
  public static final int DO = 39;
  public static final int PRINT = 19;
  public static final int STEP = 40;
  public static final int PYC = 16;
}

