
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECL_TYPE = 44;
  public static final int GE = 13;
  public static final int UMINUS = 6;
  public static final int ASIG2 = 35;
  public static final int DOUBLE = 25;
  public static final int INTEGER = 24;
  public static final int FOR = 39;
  public static final int MINUS = 3;
  public static final int OCC = 20;
  public static final int NOT = 7;
  public static final int AND = 8;
  public static final int LT = 10;
  public static final int CK = 23;
  public static final int IN = 40;
  public static final int OR = 9;
  public static final int COMMA = 19;
  public static final int DIV = 5;
  public static final int FOR_NO_VAR = 46;
  public static final int EOL = 28;
  public static final int OK = 22;
  public static final int PLUS = 2;
  public static final int IF = 37;
  public static final int CB = 18;
  public static final int LE = 11;
  public static final int SK_LINE = 29;
  public static final int EOF = 0;
  public static final int ASIG = 34;
  public static final int OB = 17;
  public static final int TRUE = 26;
  public static final int FOR_SEQ = 45;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int INTEGER_TYPE = 42;
  public static final int DOUBLE_TYPE = 41;
  public static final int EQ = 14;
  public static final int CCC = 21;
  public static final int ELSE = 38;
  public static final int WHILE = 36;
  public static final int LET = 32;
  public static final int NE = 15;
  public static final int VAR_NAME = 33;
  public static final int FALSE = 27;
  public static final int GT = 12;
  public static final int VAR = 31;
  public static final int PRINT = 16;
  public static final int PYC = 30;
  public static final int BOOLEAN_TYPE = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "UMINUS",
  "NOT",
  "AND",
  "OR",
  "LT",
  "LE",
  "GT",
  "GE",
  "EQ",
  "NE",
  "PRINT",
  "OB",
  "CB",
  "COMMA",
  "OCC",
  "CCC",
  "OK",
  "CK",
  "INTEGER",
  "DOUBLE",
  "TRUE",
  "FALSE",
  "EOL",
  "SK_LINE",
  "PYC",
  "VAR",
  "LET",
  "VAR_NAME",
  "ASIG",
  "ASIG2",
  "WHILE",
  "IF",
  "ELSE",
  "FOR",
  "IN",
  "DOUBLE_TYPE",
  "INTEGER_TYPE",
  "BOOLEAN_TYPE",
  "DECL_TYPE",
  "FOR_SEQ",
  "FOR_NO_VAR"
  };
}

