
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 07 14:42:56 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FMT_PRINT = 38;
  public static final int BOOL_TYPE = 42;
  public static final int CONST = 45;
  public static final int GE = 15;
  public static final int UMINUS = 6;
  public static final int ASIG2 = 27;
  public static final int DOUBLE = 30;
  public static final int INTEGER = 29;
  public static final int FOR = 49;
  public static final int MINUS = 3;
  public static final int OCC = 22;
  public static final int NOT = 9;
  public static final int AND = 11;
  public static final int LT = 12;
  public static final int CK = 25;
  public static final int OR = 10;
  public static final int COMMA = 18;
  public static final int INC = 7;
  public static final int DIV = 5;
  public static final int EOL = 31;
  public static final int OK = 24;
  public static final int PLUS = 2;
  public static final int MAIN = 34;
  public static final int CB = 21;
  public static final int LE = 13;
  public static final int SK_LINE = 32;
  public static final int EOF = 0;
  public static final int ASIG = 26;
  public static final int TRUE = 47;
  public static final int STRING_TYPE = 43;
  public static final int OB = 20;
  public static final int error = 1;
  public static final int FMT_PACKAGE = 36;
  public static final int MUL = 4;
  public static final int INT_TYPE = 41;
  public static final int EQ = 16;
  public static final int IMPORT = 35;
  public static final int CCC = 23;
  public static final int FUNC = 37;
  public static final int PACKAGE = 33;
  public static final int FMT_PRINTF = 40;
  public static final int NE = 17;
  public static final int VAR_NAME = 28;
  public static final int STRING = 46;
  public static final int DEC = 8;
  public static final int FALSE = 48;
  public static final int GT = 14;
  public static final int VAR = 44;
  public static final int FMT_PRINTLN = 39;
  public static final int PYC = 19;
}

