
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 16 14:55:31 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 36;
  public static final int GE = 14;
  public static final int UMINUS = 6;
  public static final int DOUBLE = 26;
  public static final int INTEGER = 25;
  public static final int FOR = 44;
  public static final int MINUS = 3;
  public static final int OCC = 21;
  public static final int NOT = 8;
  public static final int AND = 9;
  public static final int LT = 11;
  public static final int CK = 24;
  public static final int IN = 45;
  public static final int OR = 10;
  public static final int COMMA = 20;
  public static final int INC = 33;
  public static final int DIV = 5;
  public static final int EOL = 30;
  public static final int OK = 23;
  public static final int PLUS = 2;
  public static final int IF = 40;
  public static final int CB = 19;
  public static final int LE = 12;
  public static final int SK_LINE = 31;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int ASIG = 38;
  public static final int OB = 18;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int MOD = 7;
  public static final int EQ = 15;
  public static final int CCC = 22;
  public static final int ELSE = 41;
  public static final int FUNC = 47;
  public static final int WHILE = 43;
  public static final int NE = 16;
  public static final int VAR_NAME = 37;
  public static final int STRING = 27;
  public static final int DEC = 34;
  public static final int FALSE = 29;
  public static final int GT = 13;
  public static final int DP = 39;
  public static final int VAR = 35;
  public static final int LENGTH = 46;
  public static final int DO = 42;
  public static final int PRINT = 17;
  public static final int PYC = 32;
}

